blank_issues_enabled: true
contact_links:
  - name: Firefly III Documentation
    url: https://docs.firefly-iii.org/
    about: Official Firefly III documentation
  - name: Discussions
    url: https://github.com/firefly-iii/firefly-iii/discussions
    about: Ask questions in the Firefly III community discussions
